import React from "react";
import Head from "next/head";

export function GalleryHead(props) {
  return (
    <Head>
      <title>Gallery - SS Legacy</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export function CompanyHead(props) {
  return (
    <Head>
      <title>About Comany - SS Legacy</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export function HomeHead(props) {
  return (
    <Head>
      <title>SS Legacy</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
